Add fixed auto script

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -378,13 +378,13 @@ fi
 bsdinstall checksum || error "Distribution checksum failed"
 bsdinstall distextract || error "Distribution extract failed"
 
-# Pkg install zol
-pkg -r $BSDINSTALL_CHROOT pkg add /dist/zol-[0-9]*.txz || err "Failed to install ZOL"
-
 # Set up boot loader
 bsdinstall bootconfig || error "Failed to configure bootloader"
 
 bsdinstall rootpass || error "Could not set root password"
+
+# Pkg install zol
+pkg -r $BSDINSTALL_CHROOT add /dist/zol-[0-9]*.txz || err "Failed to install ZOL"
 
 trap true SIGINT	# This section is optional
 if [ "$NETCONFIG_DONE" != yes ]; then
