Add warning / error if user runs 'cc/cpp/c++' without llvm38

diff --git a/usr.bin/clang_wrappers/clang-cpp b/usr.bin/clang_wrappers/clang-cpp
--- a/usr.bin/clang_wrappers/clang-cpp
+++ b/usr.bin/clang_wrappers/clang-cpp
@@ -1,3 +1,8 @@
 #!/bin/sh
 
+if [ ! -e "/usr/local/bin/clang38" ] ; then
+  echo "ERROR: Please 'pkg install llvm38' first"
+  exit 1
+fi
+
 exec /usr/local/bin/clang-cpp38 "${@}"
