Redo the net-online service for OpenRC: 1. Make it use a lot more OpenRC built-in functions for speed 2. Make it only run the *first* probe in the foreground, all subsequent probes will happen in the background 3. Add lots of comments throughout and update the copyright 4. Add the automatic retry status to the status output.

diff --git a/etc/init.d/net-online b/etc/init.d/net-online
--- a/etc/init.d/net-online
+++ b/etc/init.d/net-online
@@ -1,48 +1,73 @@
 #!/sbin/openrc-run
-# Copyright (c) 2015 The OpenRC Authors.
-# See the Authors file at the top-level directory of this distribution and
-# https://github.com/OpenRC/openrc/blob/master/AUTHORS
-#
-# This file is part of OpenRC. It is subject to the license terms in
-# the LICENSE file found in the top-level directory of this
-# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
-# This file may not be copied, modified, propagated, or distributed
-# except according to the terms contained in the LICENSE file.
+# Copyright (c) 2018 the TrueOS Project <www.trueos.org>
+# Available under the 2-clause BSD license
 
-# Original source: https://github.com/OpenRC/openrc/blob/master/init.d/net-online.in
-
-description="Delays until the network is online or a specific timeout"
+name="net-online"
+description="Becomes active when networking is usable"
+extra_commands=retest
+interval=${retest_interval:-2}
 
 depend()
 {
-	after modules
+	after network
 	provide network-online
 }
 
-start ()
+check_online()
 {
-	local rc infinite dev found
+  #Main function: Just see if there is anything listening at the standard gateway (I.E. IP can be resolved)
+  nc -uz 255.255.255.255 111 > /dev/null 2>&1
+  ok=$?
+  if [ 0 -eq ${ok} ] && (yesno "${include_ping_test:-no}") ; then
+    #Optional: Also perform a quick single-ping of a host to verify that it is accessible
+    ping_test_host="${ping_test_host:-google.com}"
+    if [ -n "$ping_test_host" ]; then
+	ping -c 1 "$ping_test_host" > /dev/null 2>&1
+	ok=$?
+    fi
+  fi
+  if [ 0 -eq ${ok} ] ; then
+   return 0
+  else
+    return 1
+  fi
+}
 
-	ebegin "Checking to see if the network is online"
-	rc=0
-	timeout=${timeout:-120}
-	[ "$timeout" -eq 0 ] && infinite=true || infinite=false
-	while $infinite || [ "$timeout" -gt 0 ]; do
-		nc -uz 255.255.255.255 111 > /dev/null 2>&1 && break
-		sleep 1
-		: $((timeout -= 1))
-	done
-	! $infinite && [ $timeout -eq 0 ] && rc=1
-	include_ping_test=${include_ping_test:-${ping_default_gateway}}
-	if [ -n "${ping_default_gateway}" ]; then
-		ewarn "ping_default_gateway is deprecated, please use include_ping_test"
-	fi
-	if [ $rc -eq 0 ] && yesno "${include_ping_test:-no}"; then
-		ping_test_host="${ping_test_host:-google.com}"
-		if [ -n "$ping_test_host" ]; then
-			ping -c 1 "$ping_test_host" > /dev/null 2>&1
-			rc=$?
-		fi
-	fi
-	eend $rc "The network is offline"
+retest(){
+  tout=`service_get_value timeout`
+  #einfo "Retest connection: ${tout}"
+  if [ ${tout} -gt 0 ] ; then
+    : $((tout -= ${interval}))
+    service_set_value timeout ${tout}
+    if check_online ; then
+      mark_service_started net-online
+    elif [ ${tout} -gt 0 ] ; then
+      (sleep ${interval}; /sbin/service net-online retest) &
+    fi
+  else
+    #While the retest command is designed only for the internal auto-refresh system, 
+    #  it is still possible for the user to manually run it. Show an error in that situation.
+    eerror "Retest limit exceeded: service restart required"
+    return 1
+  fi
+}
+
+start(){
+  if check_online ; then
+    mark_service_started net-online
+  else
+    mark_service_inactive net-online
+    #Start the automatic retest routine in the background
+    tout=${retest_timeout:-120} #retry for 120 seconds by default
+    service_set_value timeout ${tout}
+    (sleep ${interval}; /sbin/service net-online retest) &
+  fi
+}
+
+status_pre(){
+  # If the automatic retest routine is currently running, show the status of that as well
+  tout=`service_get_value timeout`
+  if [ ${tout} -gt 0 ] ; then
+    einfo "Automatically retesting connection: ${tout} seconds remaining"
+  fi
 }
