Make /etc/init.d/dumpon act more like FreeBSD's

diff --git a/libexec/rc/etc.init.d/dumpon b/libexec/rc/etc.init.d/dumpon
--- a/libexec/rc/etc.init.d/dumpon
+++ b/libexec/rc/etc.init.d/dumpon
@@ -20,17 +20,61 @@ if [ -n "$dump_device" ] ; then
 	dumpdev="${dump_device}"
 fi
 
-start() {
-	# Setup any user requested dump device
-	if [ -n "$dumpdev" ]; then
-		ebegin "Activating kernel core dump device ($dumpdev)"
-		dumpon ${dumpdev}
-		eend $?
+dumpon_try()
+{
+	local flags
+
+	flags=${dumpon_flags}
+	if [ -n "${dumppubkey}" ]; then
+		warn "The dumppubkey variable is deprecated.  Use dumpon_flags."
+		flags="${flags} -k ${dumppubkey}"
 	fi
+	/sbin/dumpon ${flags} "${1}"
+	if [ $? -eq 0 ]; then
+		# Make a symlink in devfs for savecore
+		ln -fs "${1}" /dev/dumpdev
+		return 0
+	fi
+	ewarn "unable to specify $1 as a dump device"
+	return 1
 }
 
-stop() {
-	ebegin "Deactivating kernel core dump device"
-	dumpon off
-	eend $?
+start()
+{
+	# Enable dumpdev so that savecore can see it. Enable it
+	# early so a crash early in the boot process can be caught.
+	#
+	case ${dumpdev} in
+	[Nn][Oo] | '')
+		;;
+	[Aa][Uu][Tt][Oo])
+		dev=$(/bin/kenv -q dumpdev)
+		if [ -n "${dev}" ] ; then
+			dumpon_try "${dev}"
+			return $?
+		fi
+		while read dev mp type more ; do
+			[ "${type}" = "swap" ] || continue
+			[ -c "${dev}" ] || continue
+			dumpon_try "${dev}" 2>/dev/null && return 0
+		done </etc/fstab
+		ewarn "No suitable dump device was found." 1>&2
+		return 1
+		;;
+	*)
+		dumpon_try "${dumpdev}"
+		;;
+	esac
+}
+
+stop()
+{
+	case ${dumpdev} in
+	[Nn][Oo] | '')
+		;;
+	*)
+		rm -f /dev/dumpdev
+		/sbin/dumpon -v off
+		;;
+	esac
 }
